export const REQUEST_USERDATA_PENDING = "REQUEST_USERDATA_PENDING";
export const REQUEST_USERDATA_SUCCESS = "REQUEST_USERDATA_SUCCESS";
export const REQUEST_USERDATA_FAILED = "REQUEST_USERDATA_FAILED";
